hubble:
  relay:
    enabled: true
  ui:
    enabled: true
ipam:
  mode: kubernetes
mtu: 1340
livenessProbe:
  periodSeconds: 60
  failureThreshold: 30
readinessProbe:
  periodSeconds: 60
  failureThreshold: 30
startupProbe:
  periodSeconds: 10
  failureThreshold: 60
operator:
  livenessProbe:
    periodSeconds: 60
    failureThreshold: 30
  readinessProbe:
    periodSeconds: 60
    failureThreshold: 30
